AK: Fix binary_search signagure.
For reference, the previous signature and the new signature:

    template<typename T, typename Compare>
    T* binary_search(Span<T>, const T&, Compare = integral_compare, size_t* = nullptr)

    template<typename T, typename Compare = decltype(integral_compare<T>)>
    T* binary_search(Span<T>, const typename RemoveConst<T>::Type&, size_t* = nullptr, Compare = integral_compare)

There were some issues with the previous signature, namely:

    const int array[] = { 1, 2, 3, 4 };
    binary_search(ReadonlyBytes{ array, 4 }, 2);

This snipped produced the following error:

    error: no matching function for call to ‘binary_search(AK::Span<const int>, int)’
    note: candidate: ‘template<class T, class Compare> T* AK::binary_search(AK::Span<T>, const T&, Compare, size_t*)’
    note:   template argument deduction/substitution failed:
    note:   deduced conflicting types for parameter ‘const T’ (‘const int’ and ‘int’)

That's way the const typename RemoveConst<T>::Type is necessary. This is
not the end of the story though, because now there are issues with
implicit conversions from initializer lists to spans:

    const int array[] = { 1, 2, 3, 4 };
    binary_search({ array, 4 }, 2);

The only way to resolve this that I am aware of was to change the
initializer list to an explicit constructor call.

Another problem with the signature was that for some reason the compiler
wasn't able to deduce the type of Compare when the default argument is
used:

    const int array[] = { 1, 2, 3, 4 };

    // We use AK::integral_compare here by default.
    binary_search(ReadonlyBytes{ array, 4 }, 2);

I solved that issue by providing the default decltype(AK::integral_compare<T>)
which seemed to work. Not sure why the compiler wasn't able to figure
this out.

I also used the opportunity to switch the order of the parameters
nearby_index and compare. I believe nearby_index to be more commonly
used than custom compare methods. Also it's a lot nicer to provide
nullptr in this case rather than AK::integral_compare<Type>.